### ISSUE TITLE
Funcionalidad CRUD Buses

### ISSUE THREAD

**Issue by St3v3n-4n4** [St3v3n-4n4/Repositorio-Equipo-8#29]

**Comment by RiAn574** [comment]
Implementar función Editar

**Comment by St3v3n-4n4** [comment]
# OJO
la funcionalidad de Crear Buses, no envía a la base de datos y tampoco de forma statica
y en listar no hay conexión a base de datos

**Comment by St3v3n-4n4** [comment]
# Solucionado y Terminado



![Image](https://user-images.githubusercontent.com/108634840/190950027-52c4b0fb-7e5d-4796-89d6-4080ebfb289e.PNG)
