### ISSUE TITLE
plataforma no esta teniendo funcionalidad

### ISSUE THREAD

**Issue by St3v3n-4n4** [St3v3n-4n4/Repositorio-Equipo-8#36]
En la pagina me deja ingresar a las pestañas de crear estaciones y buses pero el resto me sale el error que aparece también en lo que es "listar rutas", y en la base de datos no me aparece estaciones guardadas y cuando intento crear algo así sea en buses o estaciones no me las sube en la base de datos ni en el listar, no se si es solo en mi pc o si son errores de la pagina como tal 

![Image](https://user-images.githubusercontent.com/106085611/191075099-fed54cc8-3780-44b4-b68d-be754b31ab9f.png)

**Comment by St3v3n-4n4** [comment]
# Revision

Puedes mostrar las capturas de las siguientes partes de `azure data studio`

Antes de Escoger la Base de Datos...

![Image](https://user-images.githubusercontent.com/108634840/191386557-7f17026c-fd62-4ada-b0f5-8df7ebd58063.PNG)

Luego verifica estos nombres que están en Rojo

![Image](https://user-images.githubusercontent.com/108634840/191386731-1a3ba962-eca3-45e9-965f-b4d2393dc1f1.PNG)

**Comment by St3v3n-4n4** [comment]
# Hipotesis

Creo que el nombre que se debe tener de la base de datos es el siguiente..

~~~
(localdb)MSSQLLocalDB:ProyectoCiclo3
~~~

y tu lo tienes como

~~~
(localdb)MSSQLLocalDB:Proyecto83Ciclo3
~~~



![Image](https://user-images.githubusercontent.com/108634840/191387119-45a26e55-0e6e-4a81-80b4-6ba18f21655c.PNG)

**Comment by St3v3n-4n4** [comment]
# Accion 
@Helenplazas26 
Creo que debes crear otra base de datos con el nombre `ProyectoCiclo3` y seguir los siguientes pasos para la migración de la Base de Datos

## Migración de Base de Datos

Adentro de `VScode` en el `terminal` usamos los siguientes `comandos`...

nos dirigimos a la carpeta `Persistencia` por medio del `terminal`
~~~
cd ProyectoCiclo3.App.Persistencia
~~~

luego hacemos la migración con el siguiente comando

~~~
dotnet ef migrations add Migracion2 --startup-project ..\ProyectoCiclo3.App.Consola\
~~~

luego actualizamos la conexión que tenemos con la base de datos

~~~
dotnet ef database update --startup-project ..\ProyectoCiclo3.App.Consola\
~~~

`Verificamos` que en la `base de datos` tengamos los nombres de las tres `entidades` 

* `Buses`
* `Estaciones`
* `Rutas`

**Comment by Helenplazas26** [comment]
#Probado 
En la pagina ya se puede agregar buses, rutas y estaciones, y también ya se actualiza bien en la base de datos


![Image](https://user-images.githubusercontent.com/106085611/192400019-374533a1-0d03-4089-9a2c-224510adbb44.png)



![Image](https://user-images.githubusercontent.com/106085611/192400049-9de73e53-5d5e-49de-801c-e9ec590a08d6.png)



![Image](https://user-images.githubusercontent.com/106085611/192400096-271e1661-af29-4685-af54-6ad02f5f642d.png)



![Image](https://user-images.githubusercontent.com/106085611/192400124-e8f9bfe7-0d16-4854-9a61-794598343ce5.png)



![Image](https://user-images.githubusercontent.com/106085611/192415944-28b0d38f-3a27-4e8f-9f1b-0f52f4495060.png)



![Image](https://user-images.githubusercontent.com/106085611/192415993-c761980e-3cc3-425e-a5a4-4e7c93ab59dc.png)

**Comment by St3v3n-4n4** [comment]
Listo, Buen Trabajo
